"""Imperial-doctrine peer playstyle data for every civ.

Authored from artifacts/audits/imperial_playstyle_design_brief.md §4.
Injected into LEGENDARY_LEADERS_TREE.html by tools/playstyle/inject_imperial.py.
"""
from __future__ import annotations

IMPERIAL_PLAYSTYLE_DATA: dict[str, dict] = {
    "Aztecs Montezuma": {
        "imperialPsTitle": "Triple Alliance Tribute Empire",
        "imperialBsProse": "Tenochtitlan sits at the heart of a tribute network: conquered altepetl ship maize, cotton, and captives back to the capital while Eagle and Jaguar veterans expand from a tightly held core.",
        "imperialCombatDoctrine": "Aggressive — staged flower-war pressure escalates into causeway expeditions that drag tribute home from broken neighbors.",
        "imperialAges": {
            "Discovery":  "Found the lake city core and scout neighboring altepetl that will eventually become tribute partners.",
            "Colonial":   "Open flower wars to blood Eagle and Jaguar cohorts and harvest the first wave of captives.",
            "Fortress":   "Lock in Triple Alliance partners and channel tribute trickles up the causeways into Tenochtitlan.",
            "Industrial": "Great Temple shipments scale with conquered cities and elite knights snowball off captive sacrifice.",
            "Imperial":   "Tribute-empire apex: causeway logistics, Eagle and Jaguar veteran mass, and forced resource conversion from every subject city.",
        },
        "imperialEcoBullets": [
            "Tribute trickle from conquered trade posts",
            "Captive sacrifice fuels Great Temple shipments",
            "Maize and cotton convoys up the causeways",
        ],
        "imperialMilitaryBullets": [
            "Eagle and Jaguar Knight veteran core",
            "Flower-war skirmish pressure feeds elite XP",
            "No standing pro army — expansion via blooded cohorts",
        ],
        "imperialDefenseBullets": [
            "Tightly held lake-city core",
            "Causeway choke-points anchor the heartland",
        ],
    },
    "British Elizabeth": {
        "imperialPsTitle": "Tudor Maritime Empire",
        "imperialBsProse": "Elizabethan England funds armies through chartered companies and Sea Dog privateers; plantations push out to map edges while a modest trained-bands militia holds the home isle.",
        "imperialCombatDoctrine": "Combined — privateer fleets and plantation outposts project power abroad while longbow-and-musket lines hold home ground.",
        "imperialAges": {
            "Discovery":  "Charter Muscovy-style trade ventures and scout coastlines for plantation candidates.",
            "Colonial":   "Sea Dogs raid for treasure while Roanoke-style outposts sprout on contested edges.",
            "Fortress":   "Joint-stock companies (Levant, EIC) start funneling trade revenue into Royal Navy investment.",
            "Industrial": "Galleon and privateer fleets dominate sea lanes; plantation outposts mature into army-funding hubs.",
            "Imperial":   "Tudor maritime apex: heavy galleon mass, chartered-company gold trickle, and plantation-forward bases on every contested edge.",
        },
        "imperialEcoBullets": [
            "Chartered-company trade-route monopolies",
            "Plantation outposts on contested map edges",
            "Privateer prize money trickle",
        ],
        "imperialMilitaryBullets": [
            "Heavy galleon and Sea Dog privateer fleet",
            "Longbow legacy fused into ranged-musket line",
            "Modest army cap, professional army deferred",
        ],
        "imperialDefenseBullets": [
            "Trained-bands militia hold the home isle",
            "Naval screen substitutes for land fortification",
        ],
    },
    "Chinese Kangxi": {
        "imperialPsTitle": "High Qing Imperium",
        "imperialBsProse": "Kangxi's Qing project: rotating Eight-Banner garrisons, Jesuit-mapped frontiers, and tributary diplomacy. Long-range pacification expeditions push out from a fortified Manchu-Han core.",
        "imperialCombatDoctrine": "Combined — banner garrisons hold the core while heavy supply trains carry pacification campaigns to the frontier.",
        "imperialAges": {
            "Discovery":  "Scout the realm and lay groundwork for Manchu, Han, and Mongol banner garrisons.",
            "Colonial":   "Plant banner cantonments in each region and start the cartographic survey of frontiers.",
            "Fortress":   "Three Feudatories pacification: long-distance expeditions with heavy supply trains.",
            "Industrial": "Galdan-campaign tempo: banners rotate to the frontier, tribute posts multiply across the map.",
            "Imperial":   "High Qing apex: full banner mass, Jesuit-mapped vision bonus, and tribute trickle from every controlled trade post.",
        },
        "imperialEcoBullets": [
            "Tribute-post bonuses scale with controlled posts",
            "Banner-territory garrisons trickle resources",
            "Cartographer scouts widen map vision",
        ],
        "imperialMilitaryBullets": [
            "Eight-Banner mass with rotating frontier duty",
            "Supply-train heavy expedition doctrine",
            "Manchu, Han, and Mongol bannermen integrated",
        ],
        "imperialDefenseBullets": [
            "Compact fortified Qing core",
            "Banner garrisons ring the heartland",
        ],
    },
    "Dutch Maurice Nassau": {
        "imperialPsTitle": "Stadtholder of an Overseas Republic",
        "imperialBsProse": "Maurice's Holland projects a VOC-administered overseas empire — Spice Islands, Ceylon, the Cape — while engineer-laid fortifications and water-line flooding hold Brabant at home.",
        "imperialCombatDoctrine": "Combined — engineer-fortified home line plus aggressive VOC fleet projection abroad.",
        "imperialAges": {
            "Discovery":  "Charter VOC-style trade ventures and scout sea lanes to the Spice Islands.",
            "Colonial":   "Plant overseas factories and drill the first Halberdier-Ruyter combined cohorts.",
            "Fortress":   "Bank-funded permanent army takes shape behind a Brabant-style fortification line.",
            "Industrial": "Hollandic water-line flooding hardens the home; VOC garrisons mature in Ceylon and the Cape.",
            "Imperial":   "Stadtholder apex: bank-cost-reduced army, engineer fortress front, and VOC fleet projecting from Holland.",
        },
        "imperialEcoBullets": [
            "Banks scale up army cost reductions",
            "VOC trade-post yields from overseas factories",
            "Spice trickle from controlled sea lanes",
        ],
        "imperialMilitaryBullets": [
            "Engineer corps and permanent professional army",
            "Halberdier-Ruyter combined drill",
            "VOC garrison fleet for overseas projection",
        ],
        "imperialDefenseBullets": [
            "Brabant-style fortification line",
            "Hollandic water-line flooding terrain trick",
        ],
    },
    "Ethiopians Menelik": {
        "imperialPsTitle": "Solomonic Imperial Restoration",
        "imperialBsProse": "Menelik's actual imperium: Adwa 1896, the southward conquest of Harar and Kaffa, and a road-net pushing out from an Entoto highland core anchored by imported European rifles.",
        "imperialCombatDoctrine": "Combined — highland citadel core plus southward expeditionary push with imported rifles and mortars.",
        "imperialAges": {
            "Discovery":  "Anchor the Entoto highland core and scout the southern provinces for conquest.",
            "Colonial":   "Marriage-and-tribute consolidation pulls rival rases into the imperial fold.",
            "Fortress":   "Imported Mosin and Gras rifles arrive; modern infantry begins displacing levies.",
            "Industrial": "Harar, Kaffa, and Sidamo campaigns push the imperial road-net south.",
            "Imperial":   "Solomonic apex: Adwa-grade rifle line, mortar and Hotchkiss artillery park, and forward-base outposts along the road-net.",
        },
        "imperialEcoBullets": [
            "Highland citadel anchors steady trickle",
            "Tribute from absorbed rases scales eco",
            "Road-net speeds villager and trade transit",
        ],
        "imperialMilitaryBullets": [
            "European-rifle modernization (Mosin, Gras, Vetterli)",
            "Mortar and Hotchkiss artillery jump",
            "Allied native rases as garrison troops",
        ],
        "imperialDefenseBullets": [
            "Entoto highland citadel core",
            "Forward-base outposts toward Harar",
        ],
    },
    "French Louis XVIII Bourbon": {
        "imperialPsTitle": "Bourbon Restoration Imperium",
        "imperialBsProse": "Bourbon revanche: a court army of Maison du Roi cavalry, plantation Antilles policy, and a late-imperial Algiers expedition — restraint at home, expedition abroad.",
        "imperialCombatDoctrine": "Defensive into expeditionary — court army holds the realm, then pivots to overseas colonial pushes.",
        "imperialAges": {
            "Discovery":  "Restore the court and rebuild Maison du Roi escort cavalry.",
            "Colonial":   "Plantation policy in the Antilles starts feeding the metropole.",
            "Fortress":   "Engineer arm inherited from the Empire reinforces frontier fortifications.",
            "Industrial": "Hundred Thousand Sons of Saint Louis: expeditionary capability returns.",
            "Imperial":   "Algiers-1830 apex: Saharan expedition force, strong artillery park, plantation Antilles trickle behind it.",
        },
        "imperialEcoBullets": [
            "Antillean plantation coin trickle",
            "Court treasury funds elite cavalry",
            "Engineer-arm tech discounts",
        ],
        "imperialMilitaryBullets": [
            "Maison du Roi elite cavalry",
            "Strong artillery and engineer corps",
            "Saharan expedition unit at Imperial",
        ],
        "imperialDefenseBullets": [
            "Legitimist court restraint — fortified core",
            "Frontier engineer fortifications",
        ],
    },
    "Germans Frederick Great": {
        "imperialPsTitle": "Brandenburg-Prussia Imperium",
        "imperialBsProse": "Frederick's Prussia: cantonal-recruited Doppelsoldner mass, Hessian mercenary loans, and oblique-order shock pushes that carve Silesia out of Habsburg territory.",
        "imperialCombatDoctrine": "Aggressive — oblique-order shock attacks driven into the enemy core, backed by Junker cavalry timing pushes.",
        "imperialAges": {
            "Discovery":  "Cantonal recruitment districts begin filling regimental rosters.",
            "Colonial":   "First Silesian War tempo — disciplined line infantry trades favorably.",
            "Fortress":   "Hessian and Württemberg mercenary loans reinforce the field army.",
            "Industrial": "Oblique-order doctrine matures; Junker officer caste sharpens cavalry timing.",
            "Imperial":   "Frederician apex: Doppelsoldner and Uhlan mass, raised army cap, mercenary shipments scaling with treasury.",
        },
        "imperialEcoBullets": [
            "Saloon shipments scale with treasury",
            "Cantonal recruitment lowers unit cost",
            "Frontier toll posts trickle coin",
        ],
        "imperialMilitaryBullets": [
            "Doppelsoldner and Uhlan mass",
            "Oblique-order shock attack doctrine",
            "Junker cavalry timing pushes",
        ],
        "imperialDefenseBullets": [
            "Cantonal-garrisoned home districts",
            "Mercenary reserve plugs frontier gaps",
        ],
    },
    "Haudenosaunee Hiawatha Iroquois": {
        "imperialPsTitle": "Confederacy Pax Iroquois",
        "imperialBsProse": "Beaver Wars empire: fur-trade dominion projected from the Five Nations homeland, Mourning War demographic absorption, and council-of-sachems diplomacy across the Great Lakes.",
        "imperialCombatDoctrine": "Aggressive — forward warband raids fan out from the homeland, absorbing captured villagers as they go.",
        "imperialAges": {
            "Discovery":  "Five Nations longhouse core takes shape; first Great Lakes scouts deploy.",
            "Colonial":   "Beaver Wars open: fur-post yields begin compounding.",
            "Fortress":   "Mourning War absorption converts captured villagers into population.",
            "Industrial": "Council diplomacy multi-fires native treaties; fur trickle exponential.",
            "Imperial":   "Pax Iroquois apex: Great Lakes trade-route control, forward warbands, and absorbed-villager pop overflow.",
        },
        "imperialEcoBullets": [
            "Fur-post yields scale exponentially",
            "Captured villagers convert to your pop",
            "Multi-fire native treaties from council diplomacy",
        ],
        "imperialMilitaryBullets": [
            "Forward warband raid mass",
            "Mourning-War absorbed warriors",
            "Lake-route ambush mobility",
        ],
        "imperialDefenseBullets": [
            "Longhouse core in the Five Nations homeland",
            "Trade-node spread provides defense in depth",
        ],
    },
    "Hausa Usman dan Fodio": {
        "imperialPsTitle": "Sokoto Caliphate",
        "imperialBsProse": "Usman's jihad-state: Sokoto-led caliphal expansion with Lifidi knight and Fula warrior cavalry, funded by trans-Saharan tax and emirate-confederation tribute.",
        "imperialCombatDoctrine": "Aggressive — caliphal cavalry expansion, daughter-emirate forward bases, scholarly conversion soft power.",
        "imperialAges": {
            "Discovery":  "Found the Sokoto core and proclaim caliphal authority over neighboring emirates.",
            "Colonial":   "Lifidi armored knights take the field; Fula warrior bands raid south.",
            "Fortress":   "Daughter emirates (Kano, Bauchi) function as forward town centers under shared bias.",
            "Industrial": "Trans-Saharan trade reorientation funnels jangali tax into the standing cavalry.",
            "Imperial":   "Sokoto apex: caliphal cavalry mass, scholar-led conversion discounts, and emirate-confederation forward presence.",
        },
        "imperialEcoBullets": [
            "Jangali pastoralist tax trickle",
            "Trans-Saharan trade reorientation",
            "Daughter-emirate forward TC bias",
        ],
        "imperialMilitaryBullets": [
            "Lifidi armored knight + Fula warrior mass",
            "Standing cavalry funded by tribute",
            "Scholar-led conversion soft power",
        ],
        "imperialDefenseBullets": [
            "Sokoto fortified core",
            "Distributed emirate confederation depth",
        ],
    },
    "Inca Pachacuti": {
        "imperialPsTitle": "Tawantinsuyu, Four Quarters",
        "imperialBsProse": "Pachacuti's founder-state: Sapa Inca authority, mit'a labor obligation, qollqa storehouses, and the Qhapaq Ñan road network binding four quarters together.",
        "imperialCombatDoctrine": "Combined — terraced fortress core, road-fed mass infantry, and mitmaq villager redirects to fuel campaigns.",
        "imperialAges": {
            "Discovery":  "Lay the Sapa Inca core and begin the qollqa storehouse network.",
            "Colonial":   "Mit'a labor obligation organizes villager output empire-wide.",
            "Fortress":   "Qhapaq Ñan road network connects TCs with movement bonus.",
            "Industrial": "Mitmaq forced relocation redirects settlers between provinces on demand.",
            "Imperial":   "Tawantinsuyu apex: terrace-fortress core, road-speed army transit, and storehouse-fed mass infantry campaigns.",
        },
        "imperialEcoBullets": [
            "Qollqa storehouse stockpile feeds campaigns",
            "Quipu census tracks every tributary",
            "Mit'a labor obligation organizes villager output",
        ],
        "imperialMilitaryBullets": [
            "Mass infantry along the Qhapaq Ñan",
            "Mitmaq redirect for army positioning",
            "Road-network transit speed bonus",
        ],
        "imperialDefenseBullets": [
            "Andean terrace-fortress core",
            "TC ring along the imperial road",
        ],
    },
    "Indians Shivaji Maharaj Maratha": {
        "imperialPsTitle": "Maratha Confederacy Empire",
        "imperialBsProse": "Shivaji's 1674 Chhatrapati coronation: a 300-fort Killa network, Ganimi Kava raid columns scaled to imperial range, and the Ashtapradhan ministerial structure speeding tech.",
        "imperialCombatDoctrine": "Aggressive raid-imperial — multi-column Ganimi Kava deep into Mughal territory anchored by hill-fort safe-points.",
        "imperialAges": {
            "Discovery":  "Claim the first Killa hill-forts and scout Mughal frontiers.",
            "Colonial":   "Ganimi Kava raid columns harass enemy supply.",
            "Fortress":   "Hill-fort network expands; fortress placement bonus on hill terrain.",
            "Industrial": "Ashtapradhan administration accelerates tech research.",
            "Imperial":   "Chhatrapati apex: 300-fort Killa network, coordinated multi-column raids, ministerial tech-speed bonus.",
        },
        "imperialEcoBullets": [
            "Tech research speed from Ashtapradhan",
            "Killa-controlled trade tolls",
            "Raid-loot trickle from raid columns",
        ],
        "imperialMilitaryBullets": [
            "Ganimi Kava multi-column raids",
            "Hill-fort safe-point army cycling",
            "Maratha cavalry-and-infantry mix",
        ],
        "imperialDefenseBullets": [
            "Killa hill-fort network",
            "Hill-terrain fortress placement bonus",
        ],
    },
    "Italians Garibaldi": {
        "imperialPsTitle": "Risorgimento Italian Empire",
        "imperialBsProse": "Garibaldi's Mille campaign scaled up: Bersaglieri rapid columns, Volunteer Redshirt mass, Mediterranean coastal hops, and a long shadow toward Africa Orientale.",
        "imperialCombatDoctrine": "Aggressive — fast volunteer columns sweep up the peninsula, with amphibious hops along the Mediterranean.",
        "imperialAges": {
            "Discovery":  "Found the Redshirt volunteer cadre and recruit the first national infantry.",
            "Colonial":   "Marsala-style amphibious landing — the Mille set off.",
            "Fortress":   "Bersaglieri rapid columns join the line; unification picks up pace.",
            "Industrial": "Continental unification consolidates; Pavisier shield infantry harden the line.",
            "Imperial":   "Risorgimento apex: volunteer mass, Bersaglieri tempo, Mediterranean amphibious projection toward African ambitions.",
        },
        "imperialEcoBullets": [
            "Anti-clerical penalty on enemy civic income",
            "Mediterranean coast trade hops",
            "Volunteer-recruitment cost discount",
        ],
        "imperialMilitaryBullets": [
            "Bersaglieri rapid columns",
            "Pavisier shield infantry line",
            "Volunteer Redshirt mass",
        ],
        "imperialDefenseBullets": [
            "Coastal amphibious mobility",
            "National-infantry holding line",
        ],
    },
    "Japanese Tokugawa Ieyasu": {
        "imperialPsTitle": "Bakufu Pax Tokugawa",
        "imperialBsProse": "Tokugawa's pax: sankin-kotai daimyo rotation, Sakoku closed-country self-sufficiency, internal canal logistics, and an Osaka Campaign late-game siege capacity.",
        "imperialCombatDoctrine": "Defensive — closed economy and shrine logistics culminate in a single Osaka-style consolidation siege.",
        "imperialAges": {
            "Discovery":  "Establish bakufu authority and shrine-economy fundamentals.",
            "Colonial":   "Sankin-kotai daimyo rotation begins inducing enemy unrest.",
            "Fortress":   "Sakoku trade closure begins; self-sufficient shrine mass replaces imports.",
            "Industrial": "Internal canal and post-road network surplus the heartland.",
            "Imperial":   "Tokugawa apex: late-game siege army with Naginata Rider hammer for an Osaka-style consolidation.",
        },
        "imperialEcoBullets": [
            "Self-sufficient shrine economy",
            "Internal canal logistics surplus",
            "Heavy negative trade bias by design",
        ],
        "imperialMilitaryBullets": [
            "Late-game siege army",
            "Naginata Rider hammer wing",
            "Sankin-kotai-induced enemy unrest",
        ],
        "imperialDefenseBullets": [
            "Closed-country home defense",
            "Post-road surveillance net",
        ],
    },
    "Lakota Gall Sioux": {
        "imperialPsTitle": "Greater Sioux Nation",
        "imperialBsProse": "Gall's pre-Reservation vision: Lakota sovereignty over Powder River, Black Hills, and Big Horn — buffalo-hunt mobility shared between economy and army, Cheyenne-Arapaho alliances scaling the lodge count.",
        "imperialCombatDoctrine": "Aggressive — maximum cavalry pressure with trail-of-burned-forts harassment to drive bluecoats off the map.",
        "imperialAges": {
            "Discovery":  "Buffalo-hunt mobility links villager and warband from the start.",
            "Colonial":   "Cheyenne-Arapaho alliance treaties scale per allied lodge.",
            "Fortress":   "Powder River and Black Hills sovereignty asserted with mounted raids.",
            "Industrial": "Anti-colonial pressure peaks — bluecoat outposts come under cavalry siege.",
            "Imperial":   "Sioux apex: all-cavalry war, lodge-scaled treaty bonuses, and burned-fort harassment over Great Plains range.",
        },
        "imperialEcoBullets": [
            "Buffalo-hunt feeds eco and army together",
            "Native treaty bonuses per allied lodge",
            "Trail-of-loot from harassed forts",
        ],
        "imperialMilitaryBullets": [
            "All-cavalry mass",
            "Inter-tribal alliance shipments",
            "Anti-colonial pressure tempo",
        ],
        "imperialDefenseBullets": [
            "Mobile-camp survivability",
            "Plains map-edge pressure on intruders",
        ],
    },
    "Maltese Valette": {
        "imperialPsTitle": "Order of St. John, Imperium of Faith",
        "imperialBsProse": "Valette's 1565 Great Siege empire: held-territory faith-state with Hospitaller corsair fleet, Tripoli-Lepanto naval projection, and chapter shipments from Catholic allies.",
        "imperialCombatDoctrine": "Defensive — bastion-anchored homeland with corsair raids and amphibious counter-strikes.",
        "imperialAges": {
            "Discovery":  "Found the Hospitaller core and recruit the first Knights.",
            "Colonial":   "Corsair fleet raids Ottoman-coast shipping for tribute.",
            "Fortress":   "Bastion lines harden Birgu and St. Elmo equivalents.",
            "Industrial": "Tripoli/Lepanto naval projection extends the order's reach.",
            "Imperial":   "Great Siege apex: Hospitaller cap raised, chapter shipments from Catholic civs, amphibious raid capability.",
        },
        "imperialEcoBullets": [
            "Chapter shipments from Catholic allies",
            "Corsair-fleet raid trickle",
            "Pilgrimage-tithe trickle to the order",
        ],
        "imperialMilitaryBullets": [
            "Hospitaller production cap raised",
            "Knightly orders as administrative caste",
            "Corsair fleet for amphibious raids",
        ],
        "imperialDefenseBullets": [
            "Bastion-anchored island core",
            "Counter-Reformation diplomatic shield",
        ],
    },
    "Mexicans Hidalgo Standard": {
        "imperialPsTitle": "Republican Imperial Reach",
        "imperialBsProse": "From insurgency to imperial reach: Hidalgo's Insurgentes scaling up into Soldado professional line, Bajio silver coin trickle, and a federal-vs-centralist pivot during the imperial transition.",
        "imperialCombatDoctrine": "Aggressive levée — campesino mass infantry scaling into a professional line, propelled by silver-mine coin.",
        "imperialAges": {
            "Discovery":  "Grito-de-Dolores cadres call up the first campesino levies.",
            "Colonial":   "Insurgentes mass starts pressuring royalist towns.",
            "Fortress":   "Bajio silver trickle hardens into a coin economy.",
            "Industrial": "First Empire briefly tested; Soldado professional line displaces militias.",
            "Imperial":   "Republican imperial reach: silver-funded Soldado mass with imperial reach to Guatemala and California.",
        },
        "imperialEcoBullets": [
            "Bajio silver-mine coin trickle",
            "Campesino-villager labor bias",
            "Federal-vs-centralist civic pivot event",
        ],
        "imperialMilitaryBullets": [
            "Insurgente to Soldado professional scale-up",
            "Republican Levee mass",
            "Reach for Guatemala and California flanks",
        ],
        "imperialDefenseBullets": [
            "Republican Levee militia center",
            "Silver-town fortification core",
        ],
    },
    "Ottomans Suleiman": {
        "imperialPsTitle": "Sublime Porte at Apex",
        "imperialBsProse": "Suleiman's 1520-66 summit: Janissary, Sipahi, and devshirme army, doubled bombard park, raised pop ceiling, and Suleymaniye-era civic works funding the campaigns.",
        "imperialCombatDoctrine": "Aggressive — Janissary line plus Sipahi wing pushed forward by a doubled bombard park.",
        "imperialAges": {
            "Discovery":  "Devshirme recruitment system inaugurated; Janissary cadre forms.",
            "Colonial":   "Sipahi feudal cavalry start riding in support of Janissary infantry.",
            "Fortress":   "Mohács-style combined arms emerge; bombards take the field.",
            "Industrial": "Vienna and Buda campaigns: bombard park expands, pop ceiling raised.",
            "Imperial":   "Suleymaniye apex: full Janissary line, Sipahi wing, doubled bombard park, devshirme reserves.",
        },
        "imperialEcoBullets": [
            "Kanun-code civic income bonus",
            "Suleymaniye public works trickle",
            "Devshirme conversion bypasses villager cost",
        ],
        "imperialMilitaryBullets": [
            "Janissary line at full mass",
            "Sipahi feudal-cavalry wing",
            "Doubled Urban-style bombard park",
        ],
        "imperialDefenseBullets": [
            "Sublime Porte fortified capital",
            "Bombard-cover defensive line",
        ],
    },
    "Portuguese Henry Navigator": {
        "imperialPsTitle": "Estado da India and Atlantic Empire",
        "imperialBsProse": "Henry's feitoria chain from Sagres to Mina to Goa: padrao trade-post upgrades, carrack-and-caravel sea lanes, and a small home army backed by a large overseas garrison fleet.",
        "imperialCombatDoctrine": "Combined — modest land force at home, overwhelming naval and feitoria garrison strength on the sea lanes.",
        "imperialAges": {
            "Discovery":  "Sagres school plans the feitoria chain; first caravels launch.",
            "Colonial":   "Mina and West African factories drop, padrao stones planted.",
            "Fortress":   "Carrack fleet matures; Atlantic sea lanes lock in.",
            "Industrial": "Goa and Estado da India project power into the Indian Ocean.",
            "Imperial":   "Sagres apex: padrao posts double yields, dock pop ceiling raised, garrison-fleet imperial reach.",
        },
        "imperialEcoBullets": [
            "Padrao posts double trade yields",
            "Spice-monopoly coin trickle",
            "Feitoria chain spans home to overseas",
        ],
        "imperialMilitaryBullets": [
            "Carrack-and-caravel naval mass",
            "Large overseas garrison fleet",
            "Modest home land army",
        ],
        "imperialDefenseBullets": [
            "Coastal feitoria-fort line",
            "Naval screen substitutes for land defense",
        ],
    },
    "Russians Ivan Terrible": {
        "imperialPsTitle": "Tsardom of All Russia",
        "imperialBsProse": "Ivan's 1547 Tsardom: Kazan and Astrakhan annexations, Streltsy permanent musketeer corps, Oprichnik shock cavalry, and Volga-Caspian river-fort expansion.",
        "imperialCombatDoctrine": "Aggressive — Streltsy mass plus Oprichnik shock terror, with river-borne expansion eastward.",
        "imperialAges": {
            "Discovery":  "Found the Tsardom core and stand up the first Streltsy company.",
            "Colonial":   "Kazan campaign begins — river-fort placements head upriver.",
            "Fortress":   "Astrakhan falls; Volga-Caspian trade trickle compounds.",
            "Industrial": "Oprichnik terror reform fields shock cavalry; brief villager debuff.",
            "Imperial":   "Tsardom apex: Streltsy line, Oprichnik shock reserve, river-fort expansion to the Caspian.",
        },
        "imperialEcoBullets": [
            "Volga-Caspian river-trade trickle",
            "Boyar terror-reform villager dip then surge",
            "River-fort toll posts",
        ],
        "imperialMilitaryBullets": [
            "Streltsy permanent musketeer corps",
            "Oprichnik shock cavalry as terror reserve",
            "Cossack Voisko frontier wing",
        ],
        "imperialDefenseBullets": [
            "River-fort defensive belt",
            "Tsardom fortified capital core",
        ],
    },
    "Spanish Isabella Castile": {
        "imperialPsTitle": "Hapsburg-Castilian Composite Empire",
        "imperialBsProse": "Isabella's successor empire projected back: post-1492 Granada launchpad, Cortes/Pizarro conquistador shipments, New World silver, and inquisitorial cathedral economy.",
        "imperialCombatDoctrine": "Aggressive — conquistador forward drops with Rodelero and Lancer punch the line; silver fleet pays for it.",
        "imperialAges": {
            "Discovery":  "Reconquista finishes; Granada becomes the launch pad.",
            "Colonial":   "First conquistador shipments cross the Atlantic.",
            "Fortress":   "New World silver fleet trickles into Castile.",
            "Industrial": "Tercio precursors mature; cathedral civic anchor multiplies shipments.",
            "Imperial":   "Hapsburg-Castilian apex: silver-funded conquistador forward bases with Rodelero and Lancer wings.",
        },
        "imperialEcoBullets": [
            "New World silver trickle",
            "Cathedral and shrine production buff",
            "Trade-route control pays the silver fleet",
        ],
        "imperialMilitaryBullets": [
            "Conquistador forward-base shipments",
            "Rodelero plus Lancer combined punch",
            "Reconquista Tercio precursor line",
        ],
        "imperialDefenseBullets": [
            "Granada-style fortified launchpad",
            "Forward operational line abroad",
        ],
    },
    "Swedes Gustavus Adolphus Swedish": {
        "imperialPsTitle": "Stormaktstiden Baltic Empire",
        "imperialBsProse": "Gustavus' Dominium Maris Baltici: Riga and Pomerania bases, mobile field artillery, Carolean line with Hakkapelit shock cavalry, and torp-system soldier-cottage trickle.",
        "imperialCombatDoctrine": "Aggressive combined arms — mobile artillery and Hakkapelit shock paired with disciplined Carolean infantry.",
        "imperialAges": {
            "Discovery":  "Torp-system soldier-cottages start producing trickle and recruits.",
            "Colonial":   "Riga and Pomeranian bases project the first Baltic fleet.",
            "Fortress":   "Mobile field artillery (leather and 3-pounder) joins the line.",
            "Industrial": "Hakkapelit cavalry shock and Carolean discipline mature together.",
            "Imperial":   "Stormaktstiden apex: mobile-artillery weight retained, Carolean infantry mass, Baltic naval reach.",
        },
        "imperialEcoBullets": [
            "Torp-system villager-soldier trickle",
            "Baltic trade-port toll",
            "Iron-and-copper Stormakt economy",
        ],
        "imperialMilitaryBullets": [
            "Mobile field artillery doctrine",
            "Carolean line infantry mass",
            "Hakkapelit shock cavalry wing",
        ],
        "imperialDefenseBullets": [
            "Baltic-coast fortified ports",
            "Combined-arms screening line",
        ],
    },
    "United States Washington": {
        "imperialPsTitle": "Manifest-Destiny Republican Imperium",
        "imperialBsProse": "Washington as Cincinnatus: declines a crown but founds a republic projecting continental empire — Continental Army professionals, federal-state militia, Sharpshooter rangers ahead of the line.",
        "imperialCombatDoctrine": "Defensive into counter-attack — restraint penalty on declared war, but bonus on counter-attack windows.",
        "imperialAges": {
            "Discovery":  "Continental Army professional cadre forms.",
            "Colonial":   "Federal-state militia split: cheap militia plus elite line available.",
            "Fortress":   "Regular musketeer mass takes the field; Sharpshooter rangers screen.",
            "Industrial": "Manifest-Destiny push opens westward — Louisiana-style annexation event.",
            "Imperial":   "Republican imperial apex: Regular line plus Sharpshooter rangers, militia surge during counter-attacks.",
        },
        "imperialEcoBullets": [
            "Federal land-grant settlement bonus",
            "Counter-attack-window resource trickle",
            "Republican-Levee militia cost discount",
        ],
        "imperialMilitaryBullets": [
            "Regular Continental Army line",
            "Sharpshooter ranger elite",
            "Federal-state militia surge",
        ],
        "imperialDefenseBullets": [
            "Restrained declared-war posture",
            "Counter-attack window force surge",
        ],
    },
    "Argentines San Martin Revolution": {
        "imperialPsTitle": "Liberation-Marshal Imperium",
        "imperialBsProse": "San Martin's project: independent Rio de la Plata, Andes-crossing liberation of Chile and Peru, Granadero a Caballo elite cavalry, and pampas cattle ranching coin.",
        "imperialCombatDoctrine": "Aggressive cavalry liberation — Granadero shock corps spearhead Andean expeditions.",
        "imperialAges": {
            "Discovery":  "Rio de la Plata core declares independence; first Granaderos drill.",
            "Colonial":   "Pampas ranching coin trickle funds the regiment.",
            "Fortress":   "1817 Andes crossing: forward base on the Chilean side.",
            "Industrial": "1821 Lima entered; Sanmartiniano protectoral centralism asserts itself.",
            "Imperial":   "Liberation-marshal apex: cavalry-dominant mass with elite Granaderos and pampas-cattle coin behind it.",
        },
        "imperialEcoBullets": [
            "Pampas cattle ranching coin trickle",
            "Liberation-tribute from freed cities",
            "Centralist civic anchor",
        ],
        "imperialMilitaryBullets": [
            "Granadero a Caballo elite shock corps",
            "Cavalry-dominant army weight",
            "Andean-expedition forward base",
        ],
        "imperialDefenseBullets": [
            "Rio de la Plata fortified core",
            "Forward operational line in Chile",
        ],
    },
    "Baja Californians Alvarado Revolution": {
        "imperialPsTitle": "Californio Departmental Frontier",
        "imperialBsProse": "Alvarado's free-state of Alta California: secularized missions become economic estates, vaquero ranchero cavalry rides the peninsula, and US-annexation looms as a late event.",
        "imperialCombatDoctrine": "Aggressive frontier raids — vaquero cavalry mass exploiting mission-fed economy.",
        "imperialAges": {
            "Discovery":  "Departmental authority asserted over peninsular missions.",
            "Colonial":   "Mission secularization redistributes estates to the eco.",
            "Fortress":   "Vaquero ranchero cavalry begin frontier raid sweeps.",
            "Industrial": "Free-state autonomy hardens; presidio garrisons strengthen.",
            "Imperial":   "Californio apex: ranchero cavalry mass, mission-estate eco, naval-interception event from US annexation.",
        },
        "imperialEcoBullets": [
            "Mission-estate redistribution buff",
            "Vaquero ranching coin trickle",
            "Frontier toll trade posts",
        ],
        "imperialMilitaryBullets": [
            "Vaquero ranchero cavalry mass",
            "Mobile frontier scatter raid style",
            "Presidio garrisons hold the missions",
        ],
        "imperialDefenseBullets": [
            "Mission-presidio fort line",
            "Late US-annexation naval-interception event",
        ],
    },
    "Barbary Barbarossa Corsair Revolution": {
        "imperialPsTitle": "Algiers-Ottoman Tributary Pirate State",
        "imperialBsProse": "Barbarossa's regency: Algiers and Tunis as Ottoman vassals with a Kapudan-Pasha fleet, corsair raid economy, and slave-market ransom diplomacy.",
        "imperialCombatDoctrine": "Aggressive — corsair fleet raids and bombarding sea-power dominate, with land force secondary.",
        "imperialAges": {
            "Discovery":  "Algiers regency claims Ottoman vassalage; first galiots launch.",
            "Colonial":   "Corsair raids start funneling captured-ship resources home.",
            "Fortress":   "Tunis added to the regency; xebec fleet expands.",
            "Industrial": "Kapudan Pasha command structure unifies Mediterranean operations.",
            "Imperial":   "Barbary apex: galiot and xebec fleet at full strength, slave-ransom coin, late heavy ship reserve.",
        },
        "imperialEcoBullets": [
            "Captured-ship resource trickle",
            "Slave-market ransom coin",
            "Tributary status grants Ottoman shipments",
        ],
        "imperialMilitaryBullets": [
            "Galiot and xebec fleet",
            "Late-imperial heavy ship",
            "Corsair raiding parties",
        ],
        "imperialDefenseBullets": [
            "Algiers fortified harbor",
            "Coastal raid-camp belt",
        ],
    },
    "Brazil Pedro Revolution": {
        "imperialPsTitle": "Empire of Brazil 1822-31",
        "imperialBsProse": "Pedro's actual empire: absolutist crown over slave-coffee-sugar economy, Hessian Imperial Guard mercenary core, and a Cisplatine naval-amphibious campaign on the Plate.",
        "imperialCombatDoctrine": "Combined — Hessian-anchored line with naval-amphibious projection along the Plate.",
        "imperialAges": {
            "Discovery":  "Septembrist proclamation; the imperial crown is assumed.",
            "Colonial":   "Plantation economy organizes coffee and sugar trickle.",
            "Fortress":   "1824 Hessian mercenary contract: Imperial Guard core forms.",
            "Industrial": "Cisplatine War (1825-28) — naval-amphibious campaign opens.",
            "Imperial":   "Brazilian imperial apex: Hessian Jager and Doppelsoldner shipments, plantation coin, river-naval reach.",
        },
        "imperialEcoBullets": [
            "Coffee and sugar plantation coin trickle",
            "Villager-as-laborer plantation bias",
            "Slave-economy production base",
        ],
        "imperialMilitaryBullets": [
            "Hessian Jager and Doppelsoldner Imperial Guard",
            "Imperial Musketeer line",
            "Naval-amphibious Cisplatine projection",
        ],
        "imperialDefenseBullets": [
            "Plantation-anchored core",
            "Coastal naval shield",
        ],
    },
    "Californians Vallejo Revolution": {
        "imperialPsTitle": "Sonoma Frontier Empire",
        "imperialBsProse": "Vallejo's military-administrative jurisdiction in northern California: defensive mission-presidio dominion, Russian-American Co. trade ties, and a Bear-Flag-Revolt collapse event late.",
        "imperialCombatDoctrine": "Defensive — hold the territory rather than expand; presidio fort line plus tallow-trade ties.",
        "imperialAges": {
            "Discovery":  "Sonoma command organizes the northern frontier.",
            "Colonial":   "Mission-presidio garrisons patrol the frontier.",
            "Fortress":   "Cattle-and-tallow trade with Fort Ross strengthens the eco.",
            "Industrial": "Presidio fort line hardens; native auxiliaries integrated.",
            "Imperial":   "Sonoma apex: defensive presidio dominion, trade-post bonus, Bear-Flag-Revolt late debuff under US pressure.",
        },
        "imperialEcoBullets": [
            "Cattle-and-tallow trade trickle",
            "Russian-American Co. trade-post bonus",
            "Mission estate distributed economic network",
        ],
        "imperialMilitaryBullets": [
            "Vaquero auxiliary cavalry",
            "Presidio garrisons hold ground",
            "Native militia mustered locally",
        ],
        "imperialDefenseBullets": [
            "Presidio fort line",
            "Late Bear-Flag-Revolt collapse event",
        ],
    },
    "Canadians Brock Revolution": {
        "imperialPsTitle": "British North American Imperium",
        "imperialBsProse": "Brock's 1812 defense: empire-defended-from-within with Tecumseh's Confederacy, blockhouse fort line, and Royal Navy lake control.",
        "imperialCombatDoctrine": "Defensive — blockhouse line plus lake-control fleet, with native-allied counter-attacks.",
        "imperialAges": {
            "Discovery":  "Upper Canada militia organize; first blockhouses go up.",
            "Colonial":   "Iroquois loyalist and Shawnee allies enter the muster.",
            "Fortress":   "Royal Navy lake squadrons assert Great Lakes control.",
            "Industrial": "Blockhouse line consolidates frontier; native confederacy peaks.",
            "Imperial":   "British North American apex: native-British alliance, blockhouse fortress at the edges, lake-control fleet.",
        },
        "imperialEcoBullets": [
            "Loyalist land-grant settlement",
            "Lake-shore fishery trickle",
            "Frontier trade-post tolls",
        ],
        "imperialMilitaryBullets": [
            "Iroquois loyalist plus Shawnee deck",
            "Royal Navy lake squadrons",
            "Militia counter-attacks",
        ],
        "imperialDefenseBullets": [
            "Blockhouse fort line on the frontier",
            "Compact fortified core",
        ],
    },
    "Central Americans Morazan Revolution": {
        "imperialPsTitle": "Federal Republic of Central America",
        "imperialBsProse": "Morazan's federal imperium: Guatemala, El Salvador, Honduras, Nicaragua, and Costa Rica under one flag — liberal-reform civic anchor, native muster, coffee and mahogany economy.",
        "imperialCombatDoctrine": "Combined — liberal-republic federal levy plus native auxiliaries spread across five provinces.",
        "imperialAges": {
            "Discovery":  "Federal flag raised over five provinces; first liberal reforms enacted.",
            "Colonial":   "Maya and Pipil militia recruitment opens.",
            "Fortress":   "Coffee plantations and mahogany lumberyards mature.",
            "Industrial": "Town center radius bonus from liberal-reform civic anchor.",
            "Imperial":   "Federal Republic apex: distributed economic network across five provinces, native muster, civic-radius bonus.",
        },
        "imperialEcoBullets": [
            "Coffee trade-post scaling",
            "Mahogany lumber-yield bonus",
            "Liberal-reform town center radius",
        ],
        "imperialMilitaryBullets": [
            "Maya and Pipil native muster",
            "Federal levy line infantry",
            "Distributed five-province army",
        ],
        "imperialDefenseBullets": [
            "Distributed economic network depth",
            "Provincial militia centers",
        ],
    },
    "Chileans OHiggins Revolution": {
        "imperialPsTitle": "Patria Nueva Republican Imperium",
        "imperialBsProse": "O'Higgins' supreme-directorship: Andean defensive empire facing Spanish reaction from Peru, Cochrane's fleet projecting up the Pacific coast, late nitrate-and-copper economy.",
        "imperialCombatDoctrine": "Defensive into projection — Andean fort-line plus Cochrane naval reach up the Pacific.",
        "imperialAges": {
            "Discovery":  "Patria Nueva government establishes Republican forms.",
            "Colonial":   "Chacabuco and Maipu fort-line warfare hardens the Andean front.",
            "Fortress":   "Cochrane fleet launched; Pacific naval projection begins.",
            "Industrial": "Republican line infantry mature; mineral economy proto-organizes.",
            "Imperial":   "Patria Nueva apex: Andean terrace-fortress placement, naval reach, late nitrate-and-copper trickle.",
        },
        "imperialEcoBullets": [
            "Late nitrate and copper trickle",
            "Andean terrace agriculture",
            "Pacific port trade tolls",
        ],
        "imperialMilitaryBullets": [
            "Balanced Republican infantry",
            "Cochrane Pacific fleet",
            "Andean fort-line garrisons",
        ],
        "imperialDefenseBullets": [
            "Andean terrace fortress placement",
            "Compact Republican citadel",
        ],
    },
    "Columbians Bolivar Colombia Revolution": {
        "imperialPsTitle": "Gran Colombia Bolivarian Imperium",
        "imperialBsProse": "Bolivar's 1819-31 imperial project: Venezuela, New Granada, Quito, and Panama under one flag with Llanero light-cavalry sweeps and forward bases planted in enemy territory each age.",
        "imperialCombatDoctrine": "Aggressive — fastest cavalry mass at Imperial, plus per-age forward-base liberation campaigns.",
        "imperialAges": {
            "Discovery":  "Gran Colombia core declared; first Llanero cadres ride.",
            "Colonial":   "Forward base planted in royalist Venezuela.",
            "Fortress":   "Boyaca-style sweep liberates New Granada.",
            "Industrial": "Quito and Panama enter the federation; tempo accelerates.",
            "Imperial":   "Bolivarian apex: Llanero Paez-style sweeps, fastest cavalry mass, caudillo-fragmentation risk if pop ceiling untapped.",
        },
        "imperialEcoBullets": [
            "Liberation-tribute from freed cities",
            "Forward operational line eco bonus",
            "Llanero ranching trickle",
        ],
        "imperialMilitaryBullets": [
            "Llanero light-cavalry mass",
            "Per-age forward-base shipments",
            "Bolivarian liberation columns",
        ],
        "imperialDefenseBullets": [
            "Forward operational line abroad",
            "Caudillo-fragmentation late risk",
        ],
    },
    "Egyptians Muhammad Ali Revolution": {
        "imperialPsTitle": "Pasha of Egypt and the Sudan",
        "imperialBsProse": "Muhammad Ali's actual imperium: Sudan 1820, Hejaz, Levant 1831-40, Crete — Nizam-i Cedid French-trained line infantry, cotton-monopoly economy, early industrialization buff.",
        "imperialCombatDoctrine": "Aggressive — French-drilled musketeer line plus Hotchkiss-style artillery push from Cairo into Sudan and the Levant.",
        "imperialAges": {
            "Discovery":  "Cairo modernizing core stands up; Nizam-i Cedid drill begins.",
            "Colonial":   "Sudan campaign 1820 — first Nizam line infantry deploy.",
            "Fortress":   "Cotton-monopoly economy organizes single-resource yield.",
            "Industrial": "Mehmet-Ali factory analog buff: early-imperial production jump.",
            "Imperial":   "Pasha apex: French-trained line, Hotchkiss-style artillery, Levant and Crete reach.",
        },
        "imperialEcoBullets": [
            "Cotton-monopoly single-resource yield",
            "Early-imperial factory analog buff",
            "Sudan campaign tribute",
        ],
        "imperialMilitaryBullets": [
            "Nizam-i Cedid French-trained line",
            "Hotchkiss-style artillery park",
            "Egyptian cavalry wing",
        ],
        "imperialDefenseBullets": [
            "Cairo highland-citadel core",
            "Suez and Levant frontier line",
        ],
    },
    "Finnish Mannerheim Revolution": {
        "imperialPsTitle": "Greater Finland Defensive Imperium",
        "imperialBsProse": "Mannerheim's Karelia ambition 1918-44: defensive imperial reach into ethnically Finnish Russian territory, Mannerheim Line entrenchment, and ski-jaeger forest mobility.",
        "imperialCombatDoctrine": "Defensive — Mannerheim Line entrenchment plus ski-jaeger mobility for forest counter-strikes.",
        "imperialAges": {
            "Discovery":  "Civil War legacy split — choose conservative or liberal recruitment lean.",
            "Colonial":   "Ski-jaeger units recruited; forest-stealth mobility online.",
            "Fortress":   "Mannerheim Line entrenched; fortress placement spikes.",
            "Industrial": "Karelia reach asserted; East Karelia ambition flares.",
            "Imperial":   "Greater Finland apex: Mannerheim Line strongpoints, ski-jaeger forest counter-strikes, late forward base.",
        },
        "imperialEcoBullets": [
            "Forest lumber and pelt trickle",
            "Civil-War recruitment lean buff",
            "Karelia border-trade trickle",
        ],
        "imperialMilitaryBullets": [
            "Ski-jaeger forest mobility",
            "Mannerheim Line garrisons",
            "Mixed conservative-liberal recruitment",
        ],
        "imperialDefenseBullets": [
            "Mannerheim Line entrenched fortress",
            "Compact fortified core",
        ],
    },
    "Hungarians Kossuth Revolution": {
        "imperialPsTitle": "Honved Republican Imperium 1848-49",
        "imperialBsProse": "Kossuth's revolutionary government: independent Hungary projecting Magyar suzerainty over Croatia, Transylvania, and Slovakia with the strongest cavalry weight among Revolution civs.",
        "imperialCombatDoctrine": "Aggressive — Honved hussar and uhlan mass, National Guard levee spam, racing Russian intervention.",
        "imperialAges": {
            "Discovery":  "Revolutionary government formed; Honved cadre assembled.",
            "Colonial":   "Hussar and uhlan regiments take the field.",
            "Fortress":   "National Guard levee spams cheap militia from town centers.",
            "Industrial": "Suzerainty pushed over Croatia and Transylvania.",
            "Imperial":   "Honved apex: strongest revolutionary cavalry weight, levee mass, Russian-intervention pressure event.",
        },
        "imperialEcoBullets": [
            "National Guard town-center cost discount",
            "Magyar plain horse trickle",
            "Levee per-TC scaling",
        ],
        "imperialMilitaryBullets": [
            "Honved hussar and uhlan mass",
            "National Guard levee militia",
            "Steppe-cavalry-wedge buildstyle",
        ],
        "imperialDefenseBullets": [
            "Cavalry-screened heartland",
            "Late Russian-intervention pressure event",
        ],
    },
    "French Canadians Papineau Revolution": {
        "imperialPsTitle": "Patriote Republican Imperium",
        "imperialBsProse": "Papineau's vision: independent Lower Canada republic with Iroquois and habitant militia (1837-38 rebellion), defensive anti-British counter-empire flavored by civic militia centers.",
        "imperialCombatDoctrine": "Defensive — civic militia plus Iroquois levy hold a Lower-Canada redoubt against British counter-attack.",
        "imperialAges": {
            "Discovery":  "Lower Canada manors organize parish recruitment.",
            "Colonial":   "Habitant militia drill at the civic militia center.",
            "Fortress":   "Iroquois levy alliance ships warriors as auxiliaries.",
            "Industrial": "Patriote republic asserts independence; defensive imperial posture.",
            "Imperial":   "Patriote apex: parish-fed militia, native warrior shipments, defensive anti-British holding line.",
        },
        "imperialEcoBullets": [
            "Manor-parish villager bonus",
            "Habitant farm trickle",
            "Iroquois treaty shipments",
        ],
        "imperialMilitaryBullets": [
            "Civic militia center mass",
            "Iroquois levy native warriors",
            "Habitant rifle militia",
        ],
        "imperialDefenseBullets": [
            "Civic militia center anchor",
            "Anti-British defensive redoubt",
        ],
    },
    "Haitians Louverture Revolution": {
        "imperialPsTitle": "Black Imperium of Saint-Domingue",
        "imperialBsProse": "Toussaint's 1801 constitution: governor for life with imperial prerogative; Dessalines later crowns himself emperor. Maroon and ex-slave mass infantry; converted estates fund the war.",
        "imperialCombatDoctrine": "Aggressive — large pop ceiling of cheap insurgent infantry, with a buff vs European civs in defensive battles.",
        "imperialAges": {
            "Discovery":  "Maroon insurgent cadres organize across the colony.",
            "Colonial":   "Plantation reorganization frees labor on sugar and coffee.",
            "Fortress":   "Ex-slave militia mass takes the field; pop ceiling rises.",
            "Industrial": "Toussaint's constitution declared; imperial prerogative asserted.",
            "Imperial":   "Saint-Domingue apex: jungle-guerrilla mass infantry, plantation-conversion eco bonus, anti-European defensive buff.",
        },
        "imperialEcoBullets": [
            "Per-converted-estate eco bonus",
            "Sugar and coffee free-labor production",
            "Captured-plantation coin",
        ],
        "imperialMilitaryBullets": [
            "Maroon and ex-slave mass infantry",
            "Cheap insurgent unit ceiling",
            "Anti-European defensive battle buff",
        ],
        "imperialDefenseBullets": [
            "Jungle guerrilla network",
            "Anti-French and anti-Spanish posture",
        ],
    },
    "Indonesians Diponegoro Revolution": {
        "imperialPsTitle": "Mataram-Yogyakarta Defensive Imperium",
        "imperialBsProse": "Diponegoro's 1825-30 Java War: sultanate-led religious imperium resisting Dutch, kraton-fort defense fused with jungle guerrilla, Bugis mercenary auxiliaries.",
        "imperialCombatDoctrine": "Defensive guerrilla — kraton-fort core plus jungle ambush, with native and Bugis mass.",
        "imperialAges": {
            "Discovery":  "Yogyakarta sultanate core organizes resistance.",
            "Colonial":   "Javanese levee plus Bugis mercenary contracts begin.",
            "Fortress":   "Kraton-fort raised; jungle guerrilla harasses Dutch lines.",
            "Industrial": "Combined kraton-and-jungle buildstyle hardens further.",
            "Imperial":   "Java War apex: raised fortress level, native auxiliary mass, food-heavy spice-and-rice trickle.",
        },
        "imperialEcoBullets": [
            "Spice and rice food trickle",
            "Heavy food bias, low coin",
            "Sultanate religious-tax trickle",
        ],
        "imperialMilitaryBullets": [
            "Native Javanese levee",
            "Bugis mercenary auxiliaries",
            "Jungle guerrilla skirmishers",
        ],
        "imperialDefenseBullets": [
            "Kraton-fort defensive core",
            "Jungle ambush map control",
        ],
    },
    "Mayans Canek Maya Revolution": {
        "imperialPsTitle": "Caste-War Indigenous Imperium",
        "imperialBsProse": "Canek's 1761 Cisteil rebellion as long-Caste-War aspiration: indigenous mass infantry, cenote-and-jungle terrain control, anti-Spanish creole resistance.",
        "imperialCombatDoctrine": "Aggressive guerrilla — cheap pop-ceiling indigenous mass plus jungle chokepoints with anti-Spanish buff.",
        "imperialAges": {
            "Discovery":  "Cisteil-style cadres call up the first indigenous levies.",
            "Colonial":   "Cenote-and-jungle terrain control sets the chokepoints.",
            "Fortress":   "Maya fort raised at chokepoint; mass infantry levy expands.",
            "Industrial": "Caste-war pressure peaks against Spanish creoles.",
            "Imperial":   "Caste-War apex: cheap pop ceiling, jungle-walling, anti-Spanish-and-Mexican combat buff.",
        },
        "imperialEcoBullets": [
            "Indigenous-villager pop bonus",
            "Henequen and milpa food trickle",
            "Cenote-controlled water tolls",
        ],
        "imperialMilitaryBullets": [
            "Indigenous mass-infantry levy",
            "Jungle-guerrilla skirmishers",
            "Anti-Spanish creole combat buff",
        ],
        "imperialDefenseBullets": [
            "Cenote-and-jungle chokepoint walling",
            "Maya fort control",
        ],
    },
    "Napoleonic France Napoleon Bonaparte Revolution": {
        "imperialPsTitle": "Premier Empire Francais",
        "imperialBsProse": "Canonical Grande Armee at full corps strength: Imperial Guard, Grand Battery, Cuirassier wing, Continental System trade-refusal, and a five-marshal shipment tree.",
        "imperialCombatDoctrine": "Aggressive combined arms — Imperial Guard infantry, Grand Battery artillery, and Cuirassier shock under marshal command.",
        "imperialAges": {
            "Discovery":  "Class-Levy conscription scaffolds the army; first marshalate posts assigned.",
            "Colonial":   "Marshal-led corps practice combined-arms maneuver.",
            "Fortress":   "Grand Battery doctrine matures; pop ceiling raised.",
            "Industrial": "Continental Blockade hardens trade refusal; Imperial Guard takes shape.",
            "Imperial":   "Premier Empire apex: Imperial Guard, Grand Battery, Cuirassier wing, pop ceiling 180, blockade penalties hammered home.",
        },
        "imperialEcoBullets": [
            "Continental Blockade hard trade penalty",
            "Class-Levy raises pop ceiling to 180",
            "Marshalate shipment tree",
        ],
        "imperialMilitaryBullets": [
            "Imperial Guard infantry",
            "Grand Battery artillery",
            "Cuirassier shock-cavalry wing",
        ],
        "imperialDefenseBullets": [
            "Forward operational line abroad",
            "Marshal corps screen the heartland",
        ],
    },
    "Peruvians Santa Cruz Peru Revolution": {
        "imperialPsTitle": "Peru-Bolivian Confederation 1836-39",
        "imperialBsProse": "Santa Cruz's actual imperium: federation of North/South Peru and Bolivia under his protectorate, Andean fort-line plus native Aymara levy, Potosi silver trickle.",
        "imperialCombatDoctrine": "Defensive into projection — terrace-fortress core plus native levy, racing the Chilean War of the Confederation collapse.",
        "imperialAges": {
            "Discovery":  "Confederation declared; Aymara levy organized.",
            "Colonial":   "Andean fort-line begins terrace-placement; Potosi silver trickles.",
            "Fortress":   "Native auxiliaries integrate into the line.",
            "Industrial": "Protectorate consolidates over three regions.",
            "Imperial":   "Confederation apex: terrace-fortress placement, silver coin trickle, late Chilean-collapse threat event.",
        },
        "imperialEcoBullets": [
            "Potosi silver coin trickle",
            "Andean terrace agriculture",
            "Confederation tribute from three regions",
        ],
        "imperialMilitaryBullets": [
            "Native Aymara levy",
            "Andean fort-line garrisons",
            "Mixed Peruvian-Bolivian line infantry",
        ],
        "imperialDefenseBullets": [
            "Andean terrace fortress placement",
            "Late Chilean-collapse pressure event",
        ],
    },
    "Revolutionary France Robespierre Revolution": {
        "imperialPsTitle": "Republican Anti-Imperium",
        "imperialBsProse": "The Terror-state at its export-revolution apex: 1794 Sister Republics (Batavian, Helvetic, Cisalpine), levee en masse mass conscription, Committee of Public Safety civic anchor.",
        "imperialCombatDoctrine": "Aggressive levee — largest infantry pop ceiling, sans-culotte free-corps auxiliaries, racing a Thermidor collapse.",
        "imperialAges": {
            "Discovery":  "Levee en masse declared; conscription begins city-by-city.",
            "Colonial":   "Sans-culotte free-corps muster as native-style auxiliaries.",
            "Fortress":   "Committee of Public Safety civic anchor centralizes production.",
            "Industrial": "Sister Republics export the revolution into Holland and Switzerland.",
            "Imperial":   "Republican apex: largest infantry ceiling, free-corps auxiliaries, brief Thermidor late debuff.",
        },
        "imperialEcoBullets": [
            "Committee of Public Safety civic centralization",
            "Levee mass-recruitment cost discount",
            "Sister-Republic tribute trickle",
        ],
        "imperialMilitaryBullets": [
            "Levee en masse infantry mass",
            "Sans-culotte free-corps auxiliaries",
            "Largest infantry pop ceiling",
        ],
        "imperialDefenseBullets": [
            "Republican Levee militia center",
            "Late Thermidor collapse risk",
        ],
    },
    "Rio Grande Canales Rosillo Revolution": {
        "imperialPsTitle": "Republic of the Rio Grande 1840",
        "imperialBsProse": "Canales' separatist republic on the Texas-Tamaulipas-Coahuila borderlands: short-lived imperial reach over Northern Mexico with vaquero and Chinaco horse mass.",
        "imperialCombatDoctrine": "Aggressive raid — fastest cavalry at Imperial, frontier-scatter buildstyle scaled up.",
        "imperialAges": {
            "Discovery":  "Borderlands republic declared; first vaquero cadres ride.",
            "Colonial":   "Chinaco lancer regiments begin border raids.",
            "Fortress":   "Frontier scatter buildstyle expands across the borderlands.",
            "Industrial": "Northern Mexico reach asserted; Centralist counter-pressure mounts.",
            "Imperial":   "Rio Grande apex: fastest cavalry, scaled-up frontier scatter, late Centralist-Mexican collapse event.",
        },
        "imperialEcoBullets": [
            "Border-raid loot trickle",
            "Vaquero ranching coin",
            "Frontier trade-post tolls",
        ],
        "imperialMilitaryBullets": [
            "Vaquero and Chinaco horse mass",
            "Fastest Imperial cavalry",
            "Border-raid frontier columns",
        ],
        "imperialDefenseBullets": [
            "Mobile frontier scatter depth",
            "Late Centralist-Mexican collapse event",
        ],
    },
    "Romanians Cuza Revolution": {
        "imperialPsTitle": "United Principalities Imperium",
        "imperialBsProse": "Cuza's 1859-66 union of Wallachia and Moldavia: proto-Romanian imperial reach toward Transylvania and Dobruja, land-reform peasant levy, mixed line-infantry trained in three traditions.",
        "imperialCombatDoctrine": "Combined — peasant levy mass plus Western-trained Dorobanti and Russian-style line, with a late Ottoman-suzerainty pivot.",
        "imperialAges": {
            "Discovery":  "Wallachia-Moldavia union proclaimed; Dorobanti cadre forms.",
            "Colonial":   "Land-reform releases peasant levies into the army.",
            "Fortress":   "Phanariot legacy lines join Western-trained Dorobanti.",
            "Industrial": "Russian-trained line and French-style Rosior dragoon integrate.",
            "Imperial":   "United Principalities apex: mixed three-tradition line, peasant militia mass, late Ottoman-suzerain to independent pivot event.",
        },
        "imperialEcoBullets": [
            "Land-reform peasant villager bonus",
            "Danubian river-trade trickle",
            "Civic militia center anchor",
        ],
        "imperialMilitaryBullets": [
            "Dorobanti Western-trained line",
            "Russian-trained line infantry",
            "Rosior French-style dragoons",
        ],
        "imperialDefenseBullets": [
            "Civic militia centers across principalities",
            "Late Ottoman-suzerain pivot event",
        ],
    },
    "South Africans Kruger Boer Revolution": {
        "imperialPsTitle": "Boer Republican Imperium",
        "imperialBsProse": "Kruger's Transvaal: gold-mine state, defensive empire against British encroachment, Commando mounted-infantry, Witwatersrand gold spike, and laager strongpoint doctrine.",
        "imperialCombatDoctrine": "Defensive — laager-anchored mounted-rifle commandos with gold-funded reserve.",
        "imperialAges": {
            "Discovery":  "Transvaal Volksraad organizes commando districts.",
            "Colonial":   "First commando-cavalry mounted-infantry units drill.",
            "Fortress":   "Witwatersrand gold mines opened; coin spikes.",
            "Industrial": "Laager defensive doctrine matures; British pressure builds.",
            "Imperial":   "Boer apex: gold-funded commando mass, semi-mobile laager strongpoints, Volksraad civic anchor.",
        },
        "imperialEcoBullets": [
            "Witwatersrand gold coin spike",
            "Volksraad civic anchor",
            "Trader-cavalry trade-post bonus",
        ],
        "imperialMilitaryBullets": [
            "Commando mounted-infantry hybrid",
            "Mounted-rifle horse-rifle mass",
            "Trader-cavalry naval mercantile compound",
        ],
        "imperialDefenseBullets": [
            "Laager strongpoint defense",
            "Defensive empire vs British pressure",
        ],
    },
    "Texians Sam Houston Texas Revolution": {
        "imperialPsTitle": "Republic of Texas 1836-46",
        "imperialBsProse": "Houston's actual republic: independent Texas claiming up the Rio Grande and into Santa Fe, Volunteer militia plus Texas Rangers, cotton-and-cattle economy, and a US-annexation 1845 windfall.",
        "imperialCombatDoctrine": "Aggressive frontier counter-punch — Volunteer militia and Texas Rangers work the borderlands.",
        "imperialAges": {
            "Discovery":  "Texas Republic declared; Volunteer militia muster.",
            "Colonial":   "Texas Rangers operate as frontier counter-punch.",
            "Fortress":   "Cotton-and-cattle economy organizes; land-grant settlement bonus.",
            "Industrial": "Rio Grande and Santa Fe claims asserted; villager pop ceiling raised.",
            "Imperial":   "Texas apex: forward operational line, Ranger raids, US-annexation 1845 federation resource influx.",
        },
        "imperialEcoBullets": [
            "Land-grant settlement villager pop bonus",
            "Cotton-and-cattle coin trickle",
            "Late US-annexation resource windfall",
        ],
        "imperialMilitaryBullets": [
            "Volunteer militia mass",
            "Texas Ranger frontier raiders",
            "Forward operational line at Rio Grande",
        ],
        "imperialDefenseBullets": [
            "Frontier counter-punch doctrine",
            "Forward operational line on the border",
        ],
    },
    "Yucatan Carrillo Puerto Revolution": {
        "imperialPsTitle": "Yucatecan Socialist Imperium",
        "imperialBsProse": "Carrillo Puerto's 1922-24 governorship: Apostle-of-the-Maya-Race agrarian-socialist regional autonomy, henequen plantation economy, Mayan auxiliary levy.",
        "imperialCombatDoctrine": "Defensive — agrarian-socialist regional autonomy with Mayan native auxiliaries holding Yucatecan ground.",
        "imperialAges": {
            "Discovery":  "Socialist governorship asserts regional autonomy.",
            "Colonial":   "Henequen plantation reorganization buffs villager output.",
            "Fortress":   "Mayan auxiliary levy ships native warriors.",
            "Industrial": "Anti-Mexican-federal stance hardens; agrarian reforms institutionalize.",
            "Imperial":   "Yucatecan socialist apex: henequen-coin trickle, Mayan native shipments, late 1924 collapse political event.",
        },
        "imperialEcoBullets": [
            "Henequen plantation coin trickle",
            "Villager-reorganization socialist buff",
            "Agrarian-reform civic anchor",
        ],
        "imperialMilitaryBullets": [
            "Mayan auxiliary native warrior shipments",
            "Indigenous-levee mass infantry",
            "Jungle guerrilla skirmishers",
        ],
        "imperialDefenseBullets": [
            "Yucatecan jungle-guerrilla network",
            "Late 1924 collapse political event",
        ],
    },
}
