"""Validate the per-nation Development subtree in LEGENDARY_LEADERS_TREE.html.

The Development subtree is generated by `tools/cardextract/refresh_dev_subtrees.py`
and documents the 17 in-game identity surfaces per civ. This validator confirms:

  1. Every non-deferred nation-node has both `<!-- DEV-START name="<slug>" -->`
     and `<!-- DEV-END name="<slug>" -->` markers.
  2. The block contains a populated `<table class="dev-table">` (no malformed
     placeholder).
  3. Every asset path referenced inside `<code class="dev-path">` exists
     on disk under the repo (caught at render time even if a file was renamed).
  4. Every `_locID=<id>` reference whose surface is mod-supplied (rev civs +
     base-civ AI/scoreboard names) resolves to a non-empty string in
     `data/strings/english/stringmods.xml`.
  5. The HTML file is in sync with the generator (no drift): re-running
     `refresh_dev_subtrees.py --check` exits 0.

Exit non-zero if any rule fails. Mirrors the patterns used by
`validate_personality_overrides.py` and `validate_art_coverage.py`.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from tools.validation.validate_html_vs_mod import CIV_TO_HOMECITY  # noqa: E402
from tools.validation.validate_personality_overrides import load_string_table  # noqa: E402

HTML_PATH = REPO / "LEGENDARY_LEADERS_TREE.html"
STRINGS = REPO / "data" / "strings" / "english" / "stringmods.xml"
GENERATOR = REPO / "tools" / "cardextract" / "refresh_dev_subtrees.py"

# Mirrors refresh_dev_subtrees.DEFERRED_SLUGS — sections without HTML nation-nodes.
DEFERRED_SLUGS = {"Americans", "Mexicans (Revolution)"}


def _expected_slugs() -> list[str]:
    return [s for s in CIV_TO_HOMECITY if s not in DEFERRED_SLUGS]


def _find_dev_blocks(text: str) -> dict[str, str]:
    """slug → block body (between markers, exclusive)."""
    out: dict[str, str] = {}
    for m in re.finditer(
        r'<!--\s*DEV-START\s+name="([^"]+)"\s*-->(.*?)<!-- DEV-END name="\1" -->',
        text,
        re.DOTALL,
    ):
        out[m.group(1)] = m.group(2)
    return out


def _asset_paths_in(block: str) -> list[str]:
    return re.findall(r'<code class="dev-path">([^<]+)</code>', block)


def _string_ids_in(block: str) -> list[str]:
    return re.findall(r'_locID=([0-9]+)', block)


def validate_dev_subtrees(repo_root: Path = REPO) -> list[str]:
    """Return a list of finding strings (empty = all pass)."""
    findings: list[str] = []

    html_path = repo_root / "LEGENDARY_LEADERS_TREE.html"
    strings_path = repo_root / "data" / "strings" / "english" / "stringmods.xml"
    generator = repo_root / "tools" / "cardextract" / "refresh_dev_subtrees.py"

    if not html_path.is_file():
        return [f"missing LEGENDARY_LEADERS_TREE.html at {html_path}"]
    if not strings_path.is_file():
        return [f"missing stringmods.xml at {strings_path}"]
    if not generator.is_file():
        return [f"missing generator at {generator}"]

    html_text = html_path.read_text(encoding="utf-8")
    strings = load_string_table(strings_path)

    blocks = _find_dev_blocks(html_text)
    expected = set(_expected_slugs())

    # Rule 1: every non-deferred slug has a block.
    missing = sorted(expected - blocks.keys())
    for slug in missing:
        findings.append(f"missing DEV-START/END block for slug {slug!r}")

    # Unexpected blocks (e.g. orphaned slug from an earlier version).
    extra = sorted(set(blocks) - expected - DEFERRED_SLUGS)
    for slug in extra:
        findings.append(f"unexpected dev block for unknown slug {slug!r}")

    # Per-block content checks.
    for slug in sorted(blocks.keys() & expected):
        body = blocks[slug]

        # Rule 2: contains a dev-table.
        if 'class="dev-table"' not in body:
            findings.append(f"{slug}: dev block missing <table class=\"dev-table\">")

        # Rule 3: asset path existence.
        for path in _asset_paths_in(body):
            # Skip personality .personality refs and any path containing escaped chars.
            cleaned = path.strip()
            if not cleaned:
                continue
            full = repo_root / cleaned
            # Engine assets (e.g. `ui\\ingame\\...`, `objects\\flags\\us_texan`) are
            # not on-disk files in this repo — they live inside .bar archives.
            # Only enforce existence for paths under known repo-tracked directories.
            tracked_prefixes = ("art/", "data/", "game/", "resources/")
            posix = cleaned.replace("\\", "/")
            if not any(posix.startswith(p) for p in tracked_prefixes):
                continue
            if not full.is_file():
                # Try the alt path (back-slash → forward-slash).
                full_alt = repo_root / posix
                if full_alt.is_file():
                    continue
                findings.append(f"{slug}: dev block references missing asset {cleaned}")

        # Rule 4: string IDs ≥ 400000 are mod-owned and must resolve.
        seen_mod_ids = {sid for sid in _string_ids_in(body) if sid.isdigit() and int(sid) >= 400000}
        for sid in seen_mod_ids:
            if not strings.get(sid):
                findings.append(f"{slug}: dev block references mod _locID={sid} which is missing or empty in stringmods.xml")

    # Rule 5: drift check — generator-output should match.
    if not findings:
        try:
            result = subprocess.run(
                [sys.executable, str(generator), "--check"],
                cwd=str(repo_root),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=120,
                check=False,
            )
        except Exception as exc:  # noqa: BLE001
            findings.append(f"drift-check failed to run generator: {exc}")
        else:
            if result.returncode != 0:
                findings.append(
                    "DRIFT: refresh_dev_subtrees.py --check reported changes. "
                    "Run `python3 tools/cardextract/refresh_dev_subtrees.py` and commit."
                )
                if result.stderr.strip():
                    findings.append(f"  stderr: {result.stderr.strip()[:400]}")

    return findings


def main() -> int:
    findings = validate_dev_subtrees(REPO)
    if findings:
        print(f"Found {len(findings)} dev-subtree validation issue(s):")
        for line in findings:
            print(f" - {line}")
        return 1
    print(f"All {len(_expected_slugs())} dev subtrees populated and in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
