#!/usr/bin/env python3
"""validate_doctrine_compliance.py — cross-check the runtime probes
emitted by `aiDoctrineProbes.xs` against the structured per-civ claims
in `playstyle_spec.json`.

This complements the existing `validate_probes_vs_spec.py` (which checks
seven coarse "did boot/wall strategy/forward base etc. fire" assertions
inferred from the HTML prose). The new validator instead consumes the
DoctrineContract-style claim bundles from `playstyle_spec.json` —
generated by `tools/playtest/extract_playstyle_spec.py` — and checks
each milestone/snapshot probe against a structured assertion set.

Inputs:
    • `playstyle_spec.json`         — structured claim bundles per civ
    • one or more match-log files   — raw `[LLP v=2 …]` probe streams

Outputs:
    • Per-civ, per-claim PASS/FAIL/UNKNOWN ledger (text + JSON)
    • Aggregate roll-up: how many civs hit each claim, which doctrines
      have systemic regressions

Exit code:
    • 0 if every civ passes every concrete claim (or only UNKNOWN)
    • 1 if any civ FAILs (`--allow-fail` to override for partial runs)
    • 2 if no probes were found in any log (test harness mis-invocation)

Probe tags consumed:
    milestone.first_dock          atMs=… count=… age=…
    milestone.first_barracks      atMs=… count=… age=…
    milestone.first_stable        atMs=… count=… age=…
    milestone.first_wall_segment  atMs=… count=… age=…
    milestone.first_fort          atMs=… count=… age=…
    milestone.first_trading_post  atMs=… count=… age=…
    milestone.first_artillery     atMs=… count=… age=…
    comp.snapshot                 ageMs=… vil=… inf=… cav=… arty=… landmil=… warship=…
    posture.snapshot              ageMs=… age=… ws=… bs=… mdist=… edist=…
                                  walls=… forts=… docks=… tposts=…

Probe → spec key wiring:
    The probe header carries (civ=<engine_name>, ldr=<gLLLeaderKey>).
    We reconstruct the spec data-name by joining civ + leader-name
    fragments. Mapping table below covers all 22 base + 26 revolution
    civs; missing entries fall back to a fuzzy lookup over the spec
    keys.

CLI:
    python3 tools/validation/validate_doctrine_compliance.py \\
        --spec playstyle_spec.json \\
        --logs path/to/match.log [path/to/another.log ...] \\
        [--out report.txt] [--json report.json] [--allow-fail]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

# ─── probe parsing ─────────────────────────────────────────────────────────

PROBE_RE = re.compile(
    r"\[LLP v=2\s+t=(\d+)\s+p=\d+\s+civ=([^\s]+)\s+ldr=([^\s]+)\s+tag=([^\]]+)\](.*)$"
)
KV_RE = re.compile(r'(\w+)=("(?:[^"\\]|\\.)*"|[^\s]+)')


@dataclass
class Probe:
    t: int
    civ: str
    ldr: str
    tag: str
    fields: dict[str, str]


def _parse_kv(s: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for m in KV_RE.finditer(s):
        v = m.group(2)
        if v.startswith('"') and v.endswith('"'):
            v = v[1:-1]
        out[m.group(1)] = v
    return out


def parse_probes(log_paths: list[Path]) -> list[Probe]:
    probes: list[Probe] = []
    for p in log_paths:
        if not p.exists():
            print(f"warn: log {p} missing", file=sys.stderr)
            continue
        with p.open(encoding="utf-8", errors="replace") as fh:
            for line in fh:
                m = PROBE_RE.search(line)
                if not m:
                    continue
                probes.append(Probe(
                    t=int(m.group(1)),
                    civ=m.group(2),
                    ldr=m.group(3),
                    tag=m.group(4).strip(),
                    fields=_parse_kv(m.group(5)),
                ))
    return probes


# ─── spec → probe key resolution ───────────────────────────────────────────

# Runtime gLLLeaderKey → HTML/spec leader slug. The engine personality
# files (wellington.personality, catherine.personality, etc.) keep the
# original AoE3 leader names because the engine uses them as the AI
# dispatch ID; the mod's HTML / spec uses the rebranded leader names
# (Elizabeth, Ivan IV, Gall) instead. Without this bridge, every probe
# from British/Russian/Lakota AIs would silently fail to resolve to a
# spec entry. Verified against `grep gLLLeaderKey leaderCommon.xs` ∆
# `html_card_decks.json` keys.
RUNTIME_TO_SPEC_LEADER = {
    "wellington": "elizabeth",   # British: engine personality 'wellington' → spec leader Elizabeth
    "catherine":  "ivan",        # Russians: engine 'catherine' → spec leader Ivan IV
    "crazyhorse": "gall",        # Lakota:   engine 'crazyhorse' → spec leader Gall
    "jean":       "valette",     # Maltese:  engine 'jean'       → spec leader Valette
    "usman":      "muhammadu",   # Hausa:    engine 'usman'      → spec leader Muhammadu Kanta
}

# When the engine emits civ=British ldr=elizabeth, we want the spec key
# "British Elizabeth". The leader fragment is appended title-cased; for
# revolutions ("RvltModNapoleonicFrance") we lowercase-match against the
# spec's leader_label/data_name slug.
def _resolve_spec_key(probe_civ: str, probe_ldr: str, spec: dict[str, Any]) -> Optional[str]:
    """Return the playstyle_spec.json key for a (civ, leader) tuple, or
    None if no fuzzy match is plausible."""
    civs = spec.get("civs", {})

    # Apply the runtime→spec leader rename bridge first, so subsequent
    # candidates use the spec-side slug (e.g. wellington → elizabeth).
    spec_ldr = RUNTIME_TO_SPEC_LEADER.get(probe_ldr.lower(), probe_ldr)

    # 1) Direct join: "British" + " " + "elizabeth" titlecase → "British Elizabeth"
    candidate = f"{probe_civ} {spec_ldr.capitalize()}"
    if candidate in civs:
        return candidate

    # 2) Slug-fuzzy: lowercase-strip the data_name and compare to civ_ldr.
    target = (probe_civ + spec_ldr).lower().replace(" ", "")
    for k in civs:
        squashed = k.lower().replace(" ", "")
        if squashed.startswith(target) or target in squashed:
            return k

    # 3) Last-ditch: prefix on civ alone (covers cases where probe_civ
    # already encodes both, e.g. some revolutions).
    for k in civs:
        if k.lower().startswith(probe_civ.lower()):
            return k

    return None


# ─── per-claim assertion runners ───────────────────────────────────────────

PASS    = "PASS"
FAIL    = "FAIL"
UNKNOWN = "UNKNOWN"

@dataclass
class ClaimResult:
    civ_key: str
    claim: str
    expected: Any
    actual: Any
    status: str
    note: str = ""


def _earliest_milestone(probes: list[Probe], tag: str) -> Optional[int]:
    """Return atMs of the earliest probe with the given tag, or None."""
    candidates = [int(p.fields.get("atMs", p.t)) for p in probes if p.tag == tag]
    return min(candidates) if candidates else None


def _last_snapshot(probes: list[Probe], tag: str) -> Optional[Probe]:
    snaps = [p for p in probes if p.tag == tag]
    return snaps[-1] if snaps else None


def _any_snapshot(probes: list[Probe], tag: str, predicate) -> bool:
    return any(predicate(p) for p in probes if p.tag == tag)


def evaluate_card_compliance(spec_key: str, ldr: str, probes: list[Probe],
                             decks: dict[str, Any]) -> list[ClaimResult]:
    """Cross-check `tech.ship name="…"` probes against the canonical
    25-card deck listed in html_card_decks.json (keyed by leader slug).

    Two assertions:
      • cards.shipped_in_deck — every card name the AI shipped must be
        present in the canonical deck (case/punctuation-normalised).
        FAIL if any shipped card is not in the deck.
      • cards.deck_used — at least one canonical card actually shipped
        during the match. FAIL if zero (likely deck-load problem).
    """
    results: list[ClaimResult] = []
    deck_ldr = RUNTIME_TO_SPEC_LEADER.get(ldr.lower(), ldr)
    deck_entry = decks.get(deck_ldr)
    if deck_entry is None:
        # No deck on file for this leader slug — record as UNKNOWN so the
        # coverage gap shows up but doesn't poison the verdict.
        results.append(ClaimResult(spec_key, "cards.deck_used",
            "≥1 deck card", None, UNKNOWN, f"no html_card_decks entry for ldr={ldr}"))
        return results

    canon = {_norm_card(c) for c in deck_entry.get("deck", [])}
    shipped = []
    for p in probes:
        if p.tag != "tech.ship":
            continue
        nm = p.fields.get("name", "")
        if nm:
            shipped.append(nm)

    if not shipped:
        results.append(ClaimResult(spec_key, "cards.deck_used",
            "≥1 deck card", 0, UNKNOWN, "no tech.ship probes (match may be too short)"))
        return results

    unknown_cards = [c for c in shipped if _norm_card(c) not in canon]
    results.append(ClaimResult(spec_key, "cards.shipped_in_deck",
        "all in canonical deck", f"{len(shipped) - len(unknown_cards)}/{len(shipped)}",
        PASS if not unknown_cards else FAIL,
        f"unknown: {unknown_cards[:3]}" if unknown_cards else ""))

    in_canon = [c for c in shipped if _norm_card(c) in canon]
    results.append(ClaimResult(spec_key, "cards.deck_used",
        "≥1 canonical card shipped", len(in_canon),
        PASS if in_canon else FAIL))

    return results


def _norm_card(name: str) -> str:
    """Card-name normaliser — lowercase + collapse non-alphanumerics."""
    return re.sub(r"[^a-z0-9]+", "", name.lower())


def evaluate_civ(spec_key: str, claims: dict[str, Any], probes: list[Probe]) -> list[ClaimResult]:
    """Run every concrete claim in `claims` against this civ's probe list.
    Each claim resolves to PASS, FAIL, or UNKNOWN. Claims with no probe
    coverage at all (e.g. the AI never built anything) → UNKNOWN."""
    results: list[ClaimResult] = []

    # 1) wall_strategy — most recent posture.snapshot ws=N must equal claim
    if "wall_strategy" in claims:
        snap = _last_snapshot(probes, "posture.snapshot")
        if snap is None:
            results.append(ClaimResult(spec_key, "wall_strategy",
                claims["wall_strategy"], None, UNKNOWN, "no posture.snapshot"))
        else:
            actual = int(snap.fields.get("ws", "-1"))
            results.append(ClaimResult(spec_key, "wall_strategy",
                claims["wall_strategy"], actual,
                PASS if actual == claims["wall_strategy"] else FAIL))

    # 2) first_military_building — relative ordering of milestones
    if "first_military_building" in claims:
        expected = claims["first_military_building"]
        first_dock     = _earliest_milestone(probes, "milestone.first_dock")
        first_barracks = _earliest_milestone(probes, "milestone.first_barracks")
        first_stable   = _earliest_milestone(probes, "milestone.first_stable")
        first_tpost    = _earliest_milestone(probes, "milestone.first_trading_post")

        firsts = {
            "dock": first_dock,
            "barracks": first_barracks,
            "stable": first_stable,
            "trading_post": first_tpost,
        }
        # Resolve expected → set of acceptable milestone names.
        expected_set: set[str]
        if expected == "dock":                  expected_set = {"dock"}
        elif expected == "barracks_or_stable":  expected_set = {"barracks", "stable"}
        elif expected == "trading_post_or_market": expected_set = {"trading_post"}
        else:                                   expected_set = {expected}

        present = {k: v for k, v in firsts.items() if v is not None}
        if not present:
            results.append(ClaimResult(spec_key, "first_military_building",
                expected, None, UNKNOWN, "no milestones fired"))
        else:
            earliest_kind = min(present, key=lambda k: present[k])
            ok = earliest_kind in expected_set
            results.append(ClaimResult(spec_key, "first_military_building",
                expected, f"{earliest_kind}@{present[earliest_kind]}ms",
                PASS if ok else FAIL))

    # 3) Time-bound milestones
    for claim, tag in [
        ("first_dock_before_ms",     "milestone.first_dock"),
        ("first_wall_before_ms",     "milestone.first_wall_segment"),
    ]:
        if claim in claims:
            atMs = _earliest_milestone(probes, tag)
            limit = claims[claim]
            if atMs is None:
                results.append(ClaimResult(spec_key, claim, f"≤{limit}",
                    None, FAIL, f"{tag} never fired"))
            else:
                results.append(ClaimResult(spec_key, claim, f"≤{limit}",
                    atMs, PASS if atMs <= limit else FAIL))

    # first_barracks_before_ms — barracks OR stable counts
    if "first_barracks_before_ms" in claims:
        b = _earliest_milestone(probes, "milestone.first_barracks")
        s = _earliest_milestone(probes, "milestone.first_stable")
        candidates = [x for x in (b, s) if x is not None]
        limit = claims["first_barracks_before_ms"]
        if not candidates:
            results.append(ClaimResult(spec_key, "first_barracks_before_ms",
                f"≤{limit}", None, FAIL, "no barracks/stable milestone"))
        else:
            best = min(candidates)
            results.append(ClaimResult(spec_key, "first_barracks_before_ms",
                f"≤{limit}", best, PASS if best <= limit else FAIL))

    # 4) prose flag claims
    if claims.get("expects_naval"):
        ok = (_earliest_milestone(probes, "milestone.first_dock") is not None
              or _any_snapshot(probes, "comp.snapshot",
                               lambda p: int(p.fields.get("warship", "0")) > 0))
        results.append(ClaimResult(spec_key, "expects_naval", True, ok,
                                   PASS if ok else FAIL))

    if claims.get("expects_treaty"):
        ok = _any_snapshot(probes, "posture.snapshot",
                           lambda p: int(p.fields.get("tposts", "0")) > 0)
        results.append(ClaimResult(spec_key, "expects_treaty", True, ok,
                                   PASS if ok else FAIL))

    if claims.get("expects_cavalry"):
        # at least one snapshot where cav > inf (army is cav-leaning)
        ok = _any_snapshot(probes, "comp.snapshot",
                           lambda p: int(p.fields.get("cav", "0"))
                                    > int(p.fields.get("inf", "0")))
        results.append(ClaimResult(spec_key, "expects_cavalry", True, ok,
                                   PASS if ok else FAIL))

    if claims.get("expects_infantry"):
        ok = _any_snapshot(probes, "comp.snapshot",
                           lambda p: int(p.fields.get("inf", "0"))
                                    > int(p.fields.get("cav", "0")))
        results.append(ClaimResult(spec_key, "expects_infantry", True, ok,
                                   PASS if ok else FAIL))

    if claims.get("expects_artillery"):
        ok = (_earliest_milestone(probes, "milestone.first_artillery") is not None
              or _any_snapshot(probes, "comp.snapshot",
                               lambda p: int(p.fields.get("arty", "0")) > 0))
        results.append(ClaimResult(spec_key, "expects_artillery", True, ok,
                                   PASS if ok else FAIL))

    # expects_forward — satisfied by milestone.first_forward_base firing
    # (state machine flipped to cForwardBaseStateActive). If the match is
    # too short to ever pick a forward base, fall back to UNKNOWN so we
    # don't penalise civs that never got past Age 2.
    if claims.get("expects_forward"):
        fwd = _earliest_milestone(probes, "milestone.first_forward_base")
        if fwd is not None:
            results.append(ClaimResult(spec_key, "expects_forward", True, fwd,
                                       PASS, f"forward base active at {fwd}ms"))
        else:
            # Distinguish "AI never advanced past Age 1" (real UNKNOWN) from
            # "AI played a long match and still never went forward" (FAIL).
            last_snap = _last_snapshot(probes, "posture.snapshot")
            played_long = last_snap is not None and \
                int(last_snap.fields.get("ageMs", "0")) > 600_000  # >10 min
            if played_long:
                results.append(ClaimResult(spec_key, "expects_forward", True,
                    False, FAIL, "no forward-base milestone after 10 min"))
            else:
                results.append(ClaimResult(spec_key, "expects_forward", True,
                    None, UNKNOWN, "match ended before forward-base window"))

    # 5) military_distance_band — final posture.snapshot mdist within [lo, hi]
    if "military_distance_band" in claims:
        lo, hi = claims["military_distance_band"]
        snap = _last_snapshot(probes, "posture.snapshot")
        if snap is None:
            results.append(ClaimResult(spec_key, "military_distance_band",
                f"[{lo},{hi}]", None, UNKNOWN, "no posture.snapshot"))
        else:
            actual = float(snap.fields.get("mdist", "0"))
            ok = lo <= actual <= hi
            results.append(ClaimResult(spec_key, "military_distance_band",
                f"[{lo},{hi}]", actual, PASS if ok else FAIL))

    return results


# ─── reporting ─────────────────────────────────────────────────────────────

def _verdict_for(results: list[ClaimResult]) -> str:
    if any(r.status == FAIL for r in results):    return FAIL
    if any(r.status == PASS for r in results):    return PASS
    return UNKNOWN


def render_text(per_civ: dict[str, list[ClaimResult]]) -> str:
    out: list[str] = []
    out.append("=" * 78)
    out.append("DOCTRINE COMPLIANCE REPORT")
    out.append("=" * 78)
    overall = {PASS: 0, FAIL: 0, UNKNOWN: 0}
    for civ_key in sorted(per_civ):
        results = per_civ[civ_key]
        verdict = _verdict_for(results)
        overall[verdict] += 1
        out.append(f"\n[{verdict}] {civ_key}  ({len(results)} claims)")
        for r in results:
            mark = {PASS: "  ✓", FAIL: "  ✗", UNKNOWN: "  ?"}[r.status]
            line = f"{mark} {r.claim}: expected={r.expected!r} actual={r.actual!r}"
            if r.note:
                line += f"  ({r.note})"
            out.append(line)

    out.append("\n" + "=" * 78)
    out.append(f"SUMMARY: {overall[PASS]} pass / {overall[FAIL]} fail "
               f"/ {overall[UNKNOWN]} unknown across {len(per_civ)} civs")
    out.append("=" * 78)
    return "\n".join(out)


def render_json(per_civ: dict[str, list[ClaimResult]]) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "civs": {
            k: {
                "verdict": _verdict_for(v),
                "claims": [
                    {"claim": r.claim, "expected": r.expected, "actual": r.actual,
                     "status": r.status, "note": r.note}
                    for r in v
                ],
            }
            for k, v in per_civ.items()
        },
    }


# ─── main ──────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--spec", type=Path,
                    default=Path("playstyle_spec.json"),
                    help="path to playstyle_spec.json")
    ap.add_argument("--logs", type=Path, nargs="+", required=True,
                    help="one or more match-log paths to scan for [LLP v=2 …]")
    ap.add_argument("--out",  type=Path, default=None,
                    help="write text report here (default stdout)")
    ap.add_argument("--json", type=Path, default=None,
                    help="also write a JSON report at this path")
    ap.add_argument("--decks", type=Path,
                    default=Path(__file__).resolve().parents[1]
                                  / "playtest" / "html_card_decks.json",
                    help="path to html_card_decks.json for card-name "
                         "compliance assertions (keyed by leader slug)")
    ap.add_argument("--allow-fail", action="store_true",
                    help="exit 0 even when some civs FAIL")
    args = ap.parse_args()

    if not args.spec.exists():
        print(f"missing spec {args.spec}", file=sys.stderr)
        return 2
    spec = json.loads(args.spec.read_text(encoding="utf-8"))

    probes = parse_probes(args.logs)
    if not probes:
        print("error: no [LLP v=2 …] probes found in any log", file=sys.stderr)
        return 2

    # Bucket probes by (civ, ldr).
    per_actor: dict[tuple[str, str], list[Probe]] = defaultdict(list)
    for p in probes:
        per_actor[(p.civ, p.ldr)].append(p)

    decks: dict[str, Any] = {}
    if args.decks.exists():
        decks = json.loads(args.decks.read_text(encoding="utf-8"))
    else:
        print(f"warn: --decks {args.decks} missing; skipping card checks",
              file=sys.stderr)

    per_civ: dict[str, list[ClaimResult]] = {}
    unmatched: list[tuple[str, str]] = []
    for (civ, ldr), plist in per_actor.items():
        spec_key = _resolve_spec_key(civ, ldr, spec)
        if spec_key is None:
            unmatched.append((civ, ldr))
            continue
        claims = spec["civs"][spec_key].get("claims", {})
        results = evaluate_civ(spec_key, claims, plist) if claims else []
        if decks:
            results.extend(evaluate_card_compliance(spec_key, ldr, plist, decks))
        if results:
            per_civ[spec_key] = results

    text = render_text(per_civ)
    if unmatched:
        text += "\n\nUnmatched probe actors (no spec entry):\n"
        for civ, ldr in unmatched:
            text += f"  - civ={civ} ldr={ldr}\n"

    if args.out:
        args.out.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)

    if args.json:
        args.json.write_text(json.dumps(render_json(per_civ), indent=2),
                             encoding="utf-8")

    has_fail = any(_verdict_for(rs) == FAIL for rs in per_civ.values())
    if has_fail and not args.allow_fail:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
