"""Dump every card (base game + all DLC + mod-specific) to a single text file.

Reads:
  - data/cards.json                {card_id: {name, desc, icon}}

Writes:
  - docs/CARD_INDEX.txt            single sorted text file, one card per block

Format per entry:
    CARD_ID                          # internal tech id
      Name: <display name>
      Icon: <icon filename or '—'>
      Desc: <description, wrapped to ~80 cols or '—' if empty>

Cards are sorted alphabetically by card_id for stable diffs.
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CARDS_PATH = REPO / "data" / "cards.json"
OUT = REPO / "docs" / "CARD_INDEX.txt"


def categorize(card_id: str) -> str:
    """Best-effort DLC/source bucket based on card-id naming convention."""
    cid = card_id.lower()
    if cid.startswith("rvltmod"):
        return "Mod (Legendary Leaders revolution civs)"
    if "revmx" in cid or "mexico" in cid or "chinaco" in cid or "salteador" in cid or "soldado" in cid or "yucateco" in cid:
        return "Mexico DLC"
    if "ethiopia" in cid or "hausa" in cid or "harambee" in cid or "menelik" in cid or "sentinel" in cid or "askari" in cid or "fodio" in cid:
        return "African Royals DLC"
    if "italian" in cid or "maltes" in cid or "condott" in cid or "schiavone" in cid or "pandour" in cid or "basilica" in cid or "wignacourt" in cid or "tongue" in cid:
        return "Knights of the Mediterranean DLC"
    if "unitedstates" in cid or "federal" in cid or "usrev" in cid or "immigrant" in cid and "european" in cid:
        return "United States DLC"
    if cid.startswith("hcxp") or "iroquois" in cid or "sioux" in cid or "aztec" in cid or "lakota" in cid or "haudenosaunee" in cid:
        return "The WarChiefs / expansion"
    if cid.startswith("hcyp") or "japan" in cid or "china" in cid or "india" in cid:
        return "The Asian Dynasties / expansion"
    if cid.startswith("hc") or cid.startswith("dehc"):
        return "Base game / Definitive Edition"
    return "Other"


def main():
    cards = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
    OUT.parent.mkdir(parents=True, exist_ok=True)

    # Group by category for readability, alphabetical within each group
    buckets: dict[str, list[tuple[str, dict]]] = {}
    for cid, info in cards.items():
        buckets.setdefault(categorize(cid), []).append((cid, info))

    total = 0
    with OUT.open("w", encoding="utf-8") as f:
        f.write("=" * 80 + "\n")
        f.write("AoE3 DE Card Index — base game + all DLC + Legendary Leaders AI mod\n")
        f.write(f"Total cards indexed: {len(cards)}\n")
        f.write(f"Source: data/cards.json  (generated by tools/cardextract/extract.py)\n")
        f.write("=" * 80 + "\n\n")

        for bucket in sorted(buckets.keys()):
            entries = sorted(buckets[bucket], key=lambda t: t[0].lower())
            f.write(f"\n{'=' * 80}\n")
            f.write(f"  {bucket}  ({len(entries)} cards)\n")
            f.write(f"{'=' * 80}\n\n")
            for cid, info in entries:
                total += 1
                name = info.get("name", "") or "—"
                icon = info.get("icon", "") or "—"
                desc = info.get("desc", "") or "—"
                f.write(f"{cid}\n")
                f.write(f"  Name: {name}\n")
                f.write(f"  Icon: {icon}\n")
                if desc != "—":
                    wrapped = textwrap.fill(
                        desc, width=76, initial_indent="  Desc: ",
                        subsequent_indent="        ",
                    )
                    f.write(wrapped + "\n")
                else:
                    f.write("  Desc: —\n")
                f.write("\n")

    print(f"wrote {OUT.relative_to(REPO)} — {total} cards across {len(buckets)} categories")


if __name__ == "__main__":
    main()
